spark.sql.extensions org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions
spark.sql.catalog.nessie org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.nessie.type nessie
spark.sql.catalog.nessie.uri http://nessie:19120/api/v2
spark.sql.catalog.nessie.ref main
spark.sql.catalog.nessie.warehouse s3://delivery-lakehouse/warehouse
spark.sql.catalog.nessie.io-impl org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.nessie.cache-enabled false
spark.sql.catalog.nessie.client.region us-east-1
spark.sql.catalog.nessie.s3.endpoint http://minio:9000
spark.sql.catalog.nessie.s3.access-key-id localminio
spark.sql.catalog.nessie.s3.secret-access-key localminio123
spark.sql.catalog.nessie.s3.path-style-access true
spark.hadoop.fs.s3a.endpoint http://minio:9000
spark.hadoop.fs.s3a.access.key localminio
spark.hadoop.fs.s3a.secret.key localminio123
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.connection.ssl.enabled false
spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem
spark.driver.extraJavaOptions -Daws.region=us-east-1
spark.executor.extraJavaOptions -Daws.region=us-east-1
spark.jars.packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.11.0,org.apache.iceberg:iceberg-aws-bundle:1.11.0,org.projectnessie.nessie-integrations:nessie-spark-extensions-3.5_2.12:0.105.3,com.clickhouse:clickhouse-jdbc:0.6.4
spark.sql.shuffle.partitions 2
spark.default.parallelism 2
