#!/usr/bin/env bash
# Initialize dedicated application users for logistics_source and nessie_metadata.
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<SQL
CREATE ROLE ${SOURCE_DB_USER} LOGIN PASSWORD '${SOURCE_DB_PASSWORD}';
CREATE ROLE ${NESSIE_DB_USER} LOGIN PASSWORD '${NESSIE_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE ${SOURCE_DB_NAME} TO ${SOURCE_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${NESSIE_DB_NAME} TO ${NESSIE_DB_USER};
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$SOURCE_DB_NAME" <<SQL
GRANT USAGE, CREATE ON SCHEMA public TO ${SOURCE_DB_USER};
ALTER SCHEMA public OWNER TO ${SOURCE_DB_USER};
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$NESSIE_DB_NAME" <<SQL
GRANT USAGE, CREATE ON SCHEMA public TO ${NESSIE_DB_USER};
ALTER SCHEMA public OWNER TO ${NESSIE_DB_USER};
SQL
